C
      COMMON /CFARF /
     &  DEN(MXNLYS)   , POR(MXNLYS)   ,
     &  DIFFM         , DISPC(MXNLYS) , DISPH(MXNLYS) , VREAL(MXNLYS) ,
     &  XPATH(MXNLYS) , RET(MXNCHN,MXNELM,MXNLYS)     ,
     &  RETC(MXNCHN,MXNELM,MXNLYS)    , FC(MXNLYS)    ,
     &  DXL(MXNLYS)   , NPX(MXNLYS)   , NXTOT
